### ISSUE TITLE
mount request

### ISSUE THREAD

**Issue by misterhsp** [hardcore-sushi/DroidFS#5] opened 2020-10-19 12:47 UTC
mounting to the filesystem would be nice if you have root on your device.

Thanks...

**Comment by hardcore-sushi** [comment] 2020-10-20 13:10
Į

**Comment by hardcore-sushi** [comment] 2020-10-20 13:12
Duplicate of [#3](https://github.com/hardcore-sushi/DroidFS/issues/3)

**Closed by hardcore-sushi** 2020-10-20 13:12 UTC
