### ISSUE TITLE
In media player change brightness and volume by gestures

### ISSUE THREAD

**Issue by tampos4** [hardcore-sushi/DroidFS#112] opened 2022-04-15 11:31 UTC
Add option to change the brightness and volume while playing video by swiping vertically up and down on the left and right side respectively on media player

Ref. - [Just Player](https://github.com/moneytoo/Player), [NewPipe](https://github.com/TeamNewPipe/NewPipe)

**Comment by hardcore-sushi** [comment] 2022-04-16 18:01
Duplicate of #88.

**Closed by hardcore-sushi** 2022-04-16 18:01 UTC
