### ISSUE TITLE
Close volume if screen is locked

### ISSUE THREAD

**Issue by CodeCubeNeo** [hardcore-sushi/DroidFS#173] opened 2022-10-08 16:58 UTC
I think this is an important feature as in if you panic and click the power button on the phone, to lock the screen, the volume should be closed as well (or at least add an option in this setting for this behavior)

**Comment by hardcore-sushi** [comment] 2022-10-09 09:55
This should be the default behavior if you have not enabled the "Keep volume open" unsafe feature. Doesn't it work for you?

**Comment by CodeCubeNeo** [comment] 2022-10-12 18:49
Could those two features be separated?

**Comment by hardcore-sushi** [comment] 2022-10-13 07:24
OK so it's a duplicate of #71.

**Closed by hardcore-sushi** 2022-10-13 07:24 UTC
