### ISSUE TITLE
Can not open gocryptfs containers with long passwords in DroidFS 2.0.0

### ISSUE THREAD

**Issue by sonntagschnee** [hardcore-sushi/DroidFS#197] opened 2023-04-23 21:29 UTC
From DroidFS 2.0.0 on I can not open my gocryptfs containers, anymore.

I created the gocryptfs 1.8 containers with SiriKali 1.4.8 and synced them to my Pixel 6a with the latest GrapheneOS, but after the DroidFS update it tells me "Failed to open the volume. Please check your password.".
And containers that I created in DroidFS with the same password won't open on my Debian stable in SiriKali 1.4.8 with gocryptfs.

**After playing around a bit, I noticed that everything works well when creating containers with shorter passwords like "hallo" or "test", but with a password consisting of 50 "a"s, I have the same problem as described in the previous paragraph.**

When downgrading back to DroidFS 1.10.1, everything works, again, and I have no problem with my long passwords. Does DroidFS 2.0.0 cut of passwords it deems too long in the new password entry forms? I can not notice because it's all "*"s.

Disclaimer: I use diceware passwords which tend to be rather long.

**Comment by Cbhack13** [comment] 2023-04-24 04:44
Can confirm I seem to be having the same issue with gocryptfs containers after upgrading to DroidFS version 2.0.0 from FDroid on Android 13 (LineageOS 20.0). FWIW, I am also using a relatively long diceware passphrase. DroidFS 1.10.1 can open my container using the same passphrase without any issues.

**Comment by Cbhack13** [comment] 2023-04-24 04:57
I saved a logcat while trying to open a container that I'm having this issue with, in case that is at all helpful:

[logcat_04-23-2023_21-01-40.txt](https://github.com/hardcore-sushi/DroidFS/files/11306684/logcat_04-23-2023_21-01-40.txt)

**Comment by plamkas** [comment] 2023-04-24 05:41
Not sure if this is related to this specific issue, but after upgrading to 2.0 I was also not able to open my existing gocryptfs containers, regardless of the password length.
I found the solution by accident: I hit the + button to create a new container and DroidFS asked me to grant access to all data, which I did. After that it worked again.

**Comment by hardcore-sushi** [comment] 2023-04-24 11:43
Thank you for the bug report. This issue should have been resolved with e83cfc97940d9a1de14956d9fc24f52ca2fea3fe. The next version will include the fix. However, this update could break things. Make sure that your volumes can be opened with the original gocryptfs or CryFS tools before updating DroidFS.

**Comment by Cbhack13** [comment] 2023-04-24 18:19
In response to plamkas, I should have mentioned that I tried uninstalling and doing a fresh install of 2.0.0, and when I added a container it also asked me for permission to access files and data, which I granted. However, I still was unable to open my container with the long passphrase, so I'm pretty sure that's unrelated.

I will check to make sure gocryptfs itself can open the container before installing any more updates, and I always keep at least one backup of my container and its gocryptfs.conf file just in case.

Thanks for the fix and for the ongoing work on this app. It's been quite useful to me for a while already, but I'm really looking forward to being able to use it with USB-OTG storage, which I understand should work with the newer versions. I move around a lot, and it'll be super helpful to be able to carry around some extra storage that I can easily access from my phone without having to worry so much about data being compromised if a thumb drive goes missing!

**Comment by hardcore-sushi** [comment] 2023-04-27 09:18
Can you please retry with v2.0.1?

**Closed** 2023-04-27 10:24 UTC

**Comment by Tvirin** [comment] 2023-05-01 19:45
After update to v2.0.1 the problem has not been solved here, i can not open hidden volume container. I get message 'Failed to open the volume. Please check your password.' but password is correct.

What should I do ? Do you have a solution?

**Comment by Cbhack13** [comment] 2023-05-01 19:59
Tvirin, I also was not immediately able to open my encrypted volume after upgrading to 2.0.1. I uninstalled the app altogether, did a fresh install, and added my container. I had to grant the app permission to access files and data, and from that point on it works fine. I suspect plamkas' method above would also work, because I'm pretty sure it's a filesystem permission issue. Have you tried that?

**Comment by hardcore-sushi** [comment] 2023-05-01 20:04
First, ensure the "All files access" permission is granted to DroidFS.

If it still doesn't work but it worked with v2.0.0*, you have to downgrade to v2.0.0, then either set up fingerprint unlocking, or change the password to an empty string (short may also work). Finally, upgrade to v2.0.1. You should now be able to remove fingerprint unlocking or restore the password.

**Comment by Tvirin** [comment] 2023-05-01 22:51
Yes "All files access" permission is granted.
I can not downgrade app, the system won't let me.
I can not change my password, I get the same message the password is incorrect.
I do not have back up, I must not uninstall the application, I will lose all data.
I do not know what to do.

**Comment by Cbhack13** [comment] 2023-05-02 04:49
@Tvirin, it should be possible to make a backup copy of a hidden volume by long-pressing it in DroidFS and selecting the "Copy to shared storage" action in the menu. However, when I created a hidden test volume on my device and tried that, the app crashed. In issue #183, @hardcore-sushi said that it should also be possible with root access to copy a hidden volume from `/data/data/hardcore.sushi.droidfs/files/volumes`, but that path does not exist on my  device.

I have filed a new issue #203 to address that. Since your problem at this point seems to be related more to not being able to make a backup copy of a hidden volume, I would suggest moving further discussion to that issue. I'm currently at a dead end on how to proceed until we get that addressed, but I'm pretty sure we'll be able to help you recover your volume once it is.

**Comment by Tvirin** [comment] 2023-05-02 07:13
"Copy to shared storage" that is what I tried to do first but I have the same problem as you, the app crashes. I completely forgot to mention that.

Thank you for trying to help me.

**Comment by Cbhack13** [comment] 2023-05-02 16:47
Okay, see the response from @hardcore-sushi to #203. If you have root access on your device you should be able to do something like the following in a terminal emulator like Termux (or `adb shell` from another computer if you prefer that) to backup your hidden volume:

`su -c cp -r /data/user/0/sushi.hardcore.droidfs/files/volumes/hiddenvolumename /storage/self/primary/`

It's possible the number after `/data/user/` may be different on your device (which you could find with `su -c ls /data/user/`), and you will of course need to replace `hiddenvolumename` with whatever the name of your hidden volume is. That should create a backup copy of your volume in the top-level directory of your shared storage. Once you've confirmed you've successfully created a backup in shared storage, it should be safe to uninstall DroidFS, install 2.0.0, add the volume from the shared storage, and follow @hardcore-sushi's instructions above.

If you don't have root access, I think you'll have to wait for the next release, and then you should be able to just use the "Copy to shared storage" method.
